import { readFile, writeFile } from "node:fs/promises";

type ReleasePlan = {
  plugins: Array<{
    name: string;
    version: string;
    tag: string;
    artifact: string;
    checksum: string;
  }>;
};

async function readPlan(file: string): Promise<ReleasePlan | null> {
  try {
    return JSON.parse(await readFile(file, "utf8")) as ReleasePlan;
  } catch {
    return null;
  }
}

function releaseUrl(tag: string) {
  const repo = process.env.GITHUB_REPOSITORY;
  const server = process.env.GITHUB_SERVER_URL || "https://github.com";
  return repo ? `${server}/${repo}/releases/tag/${tag}` : tag;
}

function runUrl() {
  const repo = process.env.GITHUB_REPOSITORY;
  const server = process.env.GITHUB_SERVER_URL || "https://github.com";
  const run = process.env.GITHUB_RUN_ID;
  return repo && run ? `${server}/${repo}/actions/runs/${run}` : null;
}

function body(plan: ReleasePlan | null, status: string) {
  const ok = status === "success";
  const lines = [
    `## ${ok ? "The plugin release has been published" : "The plugin release failed"}`,
    "",
    `Status: **${status}**`,
  ];
  const run = runUrl();
  if (run) lines.push(`Workflow run: ${run}`);
  lines.push("");

  if (!plan?.plugins.length) {
    lines.push("No releasable plugins were detected.");
  } else {
    lines.push("### Releases");
    for (const plugin of plan.plugins) {
      lines.push(
        `- **${plugin.name} ${plugin.version}**: [${plugin.tag}](${releaseUrl(plugin.tag)}), \`${plugin.artifact}\`, \`${plugin.checksum}\``,
      );
    }
  }

  lines.push("", "_Generated by the Usora plugin-aware release workflow._", "");
  return lines.join("\n");
}

const out = process.argv[2];
const plan = await readPlan("release-plan.json");
const text = body(plan, process.env.JOB_STATUS || "unknown");

if (out) {
  await writeFile(out, text);
} else {
  process.stdout.write(text);
}
